config/routes.rb
Rails.application.routes.draw do
  root to: "stores#index"
  devise_for :users, controllers:{  registrations:'users/registrations'  }
  resources :stores, only: [:index, :new, :create, :show] do
    collection do
      get 'list', 'check', 'search_keyword', 'searching_keyword', 'search_prefecture', 'searching_prefecture', 'search_bathing_fee', 'searching_bathing_fee'
    end
    resources :comments, only: [:new, :create]
  end
  resources :users, only: [:index, :show] do
    collection do
      get 'check', 'check_edit'
    end
    member do
      get 'unsubscribe', 'list'
    end
    member do
      patch 'withdrawal'
    end
  end
  resources :events, only: [:show, :new, :create]
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :store

  validates :text,       presence: true
  validates :evaluation, numericality: {
    less_than_or_equal_to: 5,
    greater_than_or_equal_to: 0.5, message: 'を入力して下さい。'
  }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: [:new]

  def new
    @store = Store.find(params[:store_id])
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to "/stores/#{@comment.store.id}"
    else
      render :new
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text, :evaluation).merge(user_id: current_user.id, store_id: params[:store_id])
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/new.html.erb
<%= render "shared/header_logo" %>

<div class="comment-wrap">
  <div class="send-wrap">
      <% if user_signed_in? %>
        <%= form_with(model: [@store, @comment], url: store_comments_path, local: true) do |f| %>
        <%= render 'shared/error_messages', model: f.object %>
        <%= f.text_area :text, placeholder: "コメントする", class: "send-box", rows: "6" %>
        <div class="form-group row" id="star">
          <div class="evaluation-text"><%= f.label :star,'評価 ', class:'col-md-3 col-form-label' %></div>
          <div><%= f.hidden_field :star, id: :review_star %></div>
        </div>
        <%= f.submit "コメント投稿", class: "send-btn" %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

<script>
  $('#star').raty({
    size     : 36,
    starOff:  '<%= asset_path('star-off.png') %>',
    starOn : '<%= asset_path('star-on.png') %>',
    starHalf: '<%= asset_path('star-half.png') %>',
    scoreName: 'comment[evaluation]',
    half: true,
  });
  </script>  