config/routes.rb
Rails.application.routes.draw do
  root to: "stores#index"
  devise_for :users, controllers:{  registrations:'users/registrations'  }
  resources :stores, only: [:index, :new, :create, :show] do
    collection do
      get 'list', 'check', 'search_keyword', 'searching_keyword', 'search_prefecture', 'searching_prefecture', 'search_bathing_fee', 'searching_bathing_fee'
    end
    resources :comments, only: [:new, :create]
  end
  resources :users, only: [:index, :show] do
    collection do
      get 'check', 'check_edit'
    end
    member do
      get 'unsubscribe', 'list'
    end
    member do
      patch 'withdrawal'
    end
  end
  resources :events, only: [:show, :new, :create]
end

app/models/store.rb
class Store < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_one_attached :image

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :prefecture
  belongs_to :rouryu
  belongs_to :outside_bath
  belongs_to :break_space

  with_options presence: true do
    VALID_PHONE_CODE_REGIX = /\A[0-9-]+\z/

    validates :store_name, length: { maximum: 30 }
    validates :description, length: { maximum: 130 }
    validates :address
    validates :phone_number, length: { maximum: 15 }, format: { with: VALID_PHONE_CODE_REGIX }
    validates :sauna_temp, length: { maximum: 3 }, numericality: { only_integer: true }
    validates :water_temp, length: { maximum: 3 }, numericality: { only_integer: true }
    validates :bathing_fee, numericality: { only_integer: true }
    validates :image
  end

  validates :prefecture_id,
            inclusion: {
              in: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
                   34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47], message: 'の項目は---以外を入力して下さい'
            }

  with_options numericality: { other_than: 1, message: 'の項目は---以外を入力して下さい' } do
    validates :rouryu_id
    validates :outside_bath_id
    validates :break_space_id
  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :authenticate_user!, only: [:new]
  before_action :create_searching_keyword, only: [:list, :search_keyword, :searching_keyword]
  before_action :create_searching_prefecture, only: [:list, :search_prefecture, :searching_prefecture]
  before_action :create_searching_bathing_fee, only: [:list, :search_bathing_fee, :searching_bathing_fee]
  before_action :search_result,
                only: [:search_keyword, :searching_keyword, :search_prefecture, :searching_prefecture, :search_bathing_fee,
                       :searching_bathing_fee]

  def index
  end

  def list
    @stores = Store.order('created_at DESC')
  end

  def search_keyword
  end

  def searching_keyword
  end

  def search_prefecture
  end

  def searching_prefecture
  end

  def search_bathing_fee
  end

  def searching_bathing_fee
  end

  def new
    @store = Store.new
  end

  def create
    @store = Store.new(store_params)
    if @store.save
      redirect_to check_stores_path
    else
      render :new
    end
  end

  def check
  end

  def show
    @store = Store.find(params[:id])
    @comments = @store.comments.includes(:user).order('created_at DESC')
  end
end

private

def store_params
  params.require(:store).permit(:store_name, :description, :image, :address, :phone_number, :bathing_fee, :sauna_temp,
                                :water_temp, :prefecture_id, :rouryu_id, :outside_bath_id, :break_space_id).merge(user_id: current_user.id)
end

def create_searching_keyword
  @p = Store.ransack(params[:q])
end

def create_searching_prefecture
  @p = Store.ransack(params[:q])
end

def create_searching_bathing_fee
  @p = Store.ransack(params[:q])
end

def search_result
  @results = @p.result.order('created_at DESC')
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/check.html.erb
<%= render "shared/header_logo" %>

<div class="check-wrap">
  <div class="check-text">
    <h3 class="check-text-top">サウナ施設の情報投稿ありがとうございます！</h3>
    <p class="check-text-bottom">ご入力していただいた情報は無事に送信されました。</p>
  </div>

  <div class="back-top-page">
    <%= link_to "TOPページへ戻る", root_path, class: "back-text" %>
  </div>
</div>

app/views/stores/index.html.erb
<main class="top-main-container">
  <div class="top-main-sauna">
    <div class="top-sauna-rgba">

      <header class="header-container">
        <div class="header-content">
          <span class="header-content-color">
          <%= link_to image_tag("sauna.png", class: "app-logo"), root_path %>
          </span>
        </div>

        <div class="header-nav">
          <ul class="header-lists-right">
            <% if user_signed_in? %>
            <li><%= link_to "サウナ施設一覧", list_stores_path, class: "stores-list-nav" %></li>
            <li><%= link_to "サウナ情報投稿", new_store_path, class: "stores-list-nav" %></li>
            <li><%= link_to "マイページ", user_path(current_user.id), class: "stores-list-nav" %></li>
            <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "stores-list-nav"  %></li>
            <% else %>
            <li><%= link_to "サウナ施設一覧", list_stores_path, class: "stores-list-nav" %></li>
            <li><%= link_to "ログイン", new_user_session_path,  class: "stores-list-nav" %></li>
            <li><%= link_to "新規登録", new_user_registration_path , class: "stores-list-nav" %></li>
            <% end %>
          </ul>
        </div>
      </header>
      <%# アイウエオ %>
      <div class="top-sauna-text">
        <h1 class="question">サウナについて知ろう?！<span class="small-question">(各文章をクリックすると詳細が表示されます。)</span></h1>
        <dl>
          <div>
            <dt>サウナとは？</dt>
            <dd>サウナとはフィンランド発祥の蒸し風呂です。また、サウナ風呂とも言われることもあります。サウナストーンと呼ばれる石をたくさん乗せたストーブを熱し、その熱と石に水をかけて発生する蒸気を利用し温度・湿度を調整します。室内の温度は50度~120度以上まであり、サウナの種類も多岐にわたります。</dd>
          </div>

          <div>
            <dt>整うとは？</dt>
            <dd>昨今、ブームとなっている、整うとは一種の陶酔感を指します。「整う」には絶対に欠かせないサイクルが存在します。それは「サウナ」、「水風呂」、「外気浴」です。これらを繰り返すことで、交感神経が刺激され、血流が良くなることで陶酔感を得やすくなります。だいたい3セット繰り返すのが良いと言われています。</dd>
          </div>

          <div>
            <dt>サウナに入る際の注意とは？</dt>
            <dd>体調がすぐれない時や、飲酒後の入浴は控えましょう。また、サウナでは体内の水分を大量に消費するので脱水症状等にならないよう水分補給はこまめにとりましょう。1セットでサウナに入る時間は個人差によりますが6分~12分が目安と言われています。</dd>
          </div>
        </dl>
    </div>

    <div class="sauna-quiz">
      <div class="sauna-top-text">
        「サウナ」や「整う」ことについて詳しくなろう！
      </div>
      <div class="route">↓↓</div>
      <%= link_to "サウナクイズに挑戦！！", users_path %>
    </div>

      <footer class="footer-container">
        <div class="caution">※サウナに入る際はルールとマナーを守り、体調が悪い時は入浴を避けましょう。</div>
        <div class="copy-rights"><%= render "shared/footer_logo"%></div>
      </footer>
  </div>
</main>

app/views/stores/list.html.erb
<%= render "shared/header_logo" %>

<div class="list-search-wrap">
  <ul class="left-search-list">
    <li><%= link_to 'キーワードから探す', search_keyword_stores_path%></li>
    <li><%= link_to '都道府県から探す', search_prefecture_stores_path %></li>
    <li><%= link_to '入浴料から探す', search_bathing_fee_stores_path %></li>
  </ul>

  <ul class="right-content">
    <li><%= link_to '施設情報を投稿する', new_store_path %></li>
  </ul>
</div>

<div class="list-wrapper">
  <div class="header-list-content">
    <h2 class="header-list-text">
      施設一覧画面（新着順）
      <p class="list-text-head">※各施設名または写真をクリックすると詳細ページへアクセスできます！</p>
    </h2>
  </div>
  <ul class="list-page-wrap">
    <% @stores.each do |store| %>
      <li class="list-list">
        <div class="store-img-content">
          <%= link_to image_tag(store.image, class: "store-img"), store_path(store.id) %>
        </div>
        <div class="store-name-content">
          <div class="name-content"><%= link_to store.store_name, store_path(store.id) %></div>
          <div class="desc-content"><%= store.description %></div>
        </div>
      </li>
    <% end %>
  </ul>
</div>

app/views/stores/new.html.erb
<%= render "shared/header_logo" %>

<%= form_with model: @store, url: stores_path, class: 'stores-new-main', local: true do |f| %>
  <div class="new-form-wrap">
    <div class="form-header">
      <h1 class="new-form-header-text">
        サウナ施設情報投稿
      </h1>
    </div>

    <%= render 'shared/error_messages', model: f.object %>

    <div class="notes"><i class="fas fa-hot-tub"></i><span class="notes-text">マークの箇所は入力必須となります。</span></div>

    <div class="img-wrap">
      <div class="new-font-letter">
        施設画像
        <span><i class="fas fa-hot-tub"></i></span>
      </div>
      <div class="img-upload">
        <p>ファイルを選択し、アップロードしてください。</p>
        <%= f.file_field :image, id:"store-item" %>
      </div>
      <br>
      <div id="image-list"></div>
    </div>

    <div class="new-stores">
      <div class="new-font-letter">
        施設名
        <span><i class="fas fa-hot-tub"></i></span>
      </div>
      <%= f.text_area :store_name, class:"new-area", id:"new-name", placeholder:"施設名を入力してください (30文字まで)", maxlength:"30" %>
    </div>

    <div class="new-stores">
      <div class="new-font-letter">
        都道府県
        <span><i class="fas fa-hot-tub"></i></span>
      </div>
      <%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name, {include_blank: '---'}, class:"new-select") %>
    </div>

    <div class="new-stores">
      <div class="new-font-letter">
        住所
        <span><i class="fas fa-hot-tub"></i></span>
      </div>
      <%= f.text_field :address, class:"new-field", id:"new-name",  placeholder:"住所を入力してください" %>
    </div>

    <div class="new-stores">
      <div class="new-font-letter">
        電話番号
        <span><i class="fas fa-hot-tub"></i></span>
      </div>
      <%= f.text_field :phone_number, class:"new-field", id:"new-name", placeholder:"例)090-1234-5678" %>
    </div>

    <div class="new-stores">
      <div class="new-font-letter">
        入浴料
        <span><i class="fas fa-hot-tub"></i></span>
      </div>
      <div class="new-stores-inside">
        <div class="new-stores-left"><%= f.text_field :bathing_fee, class:"new-field-small", id:"new-name", placeholder:"例) 1000" %></div>
        <p>円</p>
      </div>
    </div>

    <div class="new-stores">
      <div class="new-font-letter">
        サウナ室温度
        <span><i class="fas fa-hot-tub"></i></span>
      </div>
      <div class="new-stores-inside">
        <div class="new-stores-left"><%= f.text_field :sauna_temp, class:"new-field-small", id:"new-name", placeholder:"例) 100" %></div>
        <p>℃</p>
      </div>
    </div>

    <div class="new-stores">
      <div class="new-font-letter">
        水風呂温度
        <span><i class="fas fa-hot-tub"></i></span>
      </div>
      <div class="new-stores-inside">
        <div class="new-stores-left"><%= f.text_field :water_temp, class:"new-field-small", id:"new-name", placeholder:"例) 15" %></div>
        <p>℃</p>
      </div>
    </div>

    <div class="new-stores">
      <div class="new-font-letter">
        オートロウリュ（頻度）
        <span><i class="fas fa-hot-tub"></i></span>
      </div>
     <%= f.collection_select(:rouryu_id, Rouryu.all, :id, :name, {}, class:"new-select") %>
    </div>

    <div class="new-stores">
      <div class="new-font-letter">
        外気浴スペース
        <span><i class="fas fa-hot-tub"></i></span>
      </div>
      <%= f.collection_select(:outside_bath_id, OutsideBath.all, :id, :name, {}, class:"new-select") %>
    </div>

    <div class="new-stores">
      <div class="new-font-letter">
        休憩スペース
        <span><i class="fas fa-hot-tub"></i></span>
      </div>
      <%= f.collection_select(:break_space_id, BreakSpace.all, :id, :name, {}, class:"new-select") %>
    </div>

    <div class="store-explain">
      <div class="new-font-letter">
        施設の紹介文
        <span><i class="fas fa-hot-tub"></i></span>
      </div>
      <%= f.text_area :description, class:"new-text-explain", id:"new-info", placeholder:"投稿する施設の紹介文を入力して下さい (130文字まで) (例) 温度が非常に高く、カラッとしたサウナです。発汗性は人によると思いますが、あまり高くないです。)",rows:"7",maxlength:"130" %>
    </div>

    <p class="stores-notes">
      ※情報は的確に入力をお願い致します。<br>
      不明確な情報と判断した場合、投稿を削除させていただく場合がございます。
    </p>

    <div class="store-btn">
      <%= f.submit "送信する", class:"post-btn" %>
      <%= link_to 'TOPページへ戻る', root_path, class:"back-btn" %>
    </div>
    
  </div>
<% end %>

app/views/stores/search_bathing_fee.html.erb
<%= render "shared/header_logo" %>

<%= search_form_for @p, url: searching_bathing_fee_stores_path do |f| %>
  <div class="search-box-wrap">
    <div class="search-box">
      <p>入浴料検索</p>
      <%= f.radio_button :bathing_fee_lteq, '' %>
      指定なし
      <%= f.radio_button :bathing_fee_lteq, '1000' %>
      1000円以下
      <%= f.radio_button :bathing_fee_lteq, '2000' %>
      2000円以下
      <%= f.radio_button :bathing_fee_lteq, '3000' %>
      3000円以下
      <br>
      <%= f.submit '検索', class:"bathing-fee-search-btn" %>
    </div>
  </div>
<% end %>

app/views/stores/search_keyword.html.erb
<%= render "shared/header_logo" %>

<%= search_form_for @p, url: searching_keyword_stores_path do |f| %>
  <div class="search-box-wrap">
    <div class="search-box">
      <p>キーワード検索</p>
     <div>
      <%= f.search_field :store_name_or_description_cont, placeholder: "キーワードを入力して下さい", class: "form-control" %>
     </div>
      <%= f.submit '検索', class:"keyword-search-btn" %>
    </div>
  </div>
<% end %>

app/views/stores/search_prefecture.html.erb
<%= render "shared/header_logo" %>

<%= search_form_for @p, url: searching_prefecture_stores_path do |f| %>
  <div class="search-box-wrap">
    <div class="search-box">
      <p>都道府県検索</p>
      <%= f.collection_select :prefecture_id_eq, Prefecture.all, :id, :name, {include_blank: '指定なし'},{class:"select-box", id:"prefecture-categorty"} %>
      <br>
      <%= f.submit '検索', class:"prefecture-search-btn" %>
    </div>
  </div>
<% end %>

app/views/stores/searching_bathing_fee.html.erb
<%= render "shared/header_logo" %>

<div class="list-wrapper">

<%= search_form_for @p, url: searching_bathing_fee_stores_path do |f| %>
  <div class="search-box-wrap">
    <div class="search-box">
      <p>入浴料</p>
      <%= f.radio_button :bathing_fee_lteq, '' %>
      指定なし
      <%= f.radio_button :bathing_fee_lteq, '1000' %>
      1000円以下
      <%= f.radio_button :bathing_fee_lteq, '2000' %>
      2000円以下
      <%= f.radio_button :bathing_fee_lteq, '3000' %>
      3000円以下
      <br>
      <%= f.submit '検索', class:"bathing-fee-search-btn" %>
    </div>
  </div>
<% end %>

  <% if @p.result.exists? %>
    <div class="header-list-content">
      <h2 class="header-list-text">
        施設一覧画面
        <p class="list-text-head">※各施設名または写真をクリックすると詳細ページへアクセスできます！</p>
      </h2>
    </div>
  <% end %>

  <ul class="list-page-wrap">
  <% if @results.length != 0 %>
    <% @results.each do |result| %>
      <li class="list-list">
        <div class="store-img-content">
          <%= link_to image_tag(result.image, class: "store-img"), store_path(result) %>
        </div>
        <div class="store-name-content">
          <div class="name-content"><%= link_to result.store_name, store_path(result) %></div>
          <div class="desc-content"><%= result.description %></div>
        </div>
      </li>
    <% end %>
  </ul>
  <% else %>

  <div class="check-wrap">
    <p class="empty-result">該当する施設はありませんでした。</p>

    <div class="back-top-page">
      <%= link_to "TOPページへ戻る", root_path, class: "back-text" %>
    </div>
  </div>
  <% end %>
</div>

app/views/stores/searching_keyword.html.erb
<%= render "shared/header_logo" %>

<%= search_form_for @p, url: searching_keyword_stores_path do |f| %>
  <div class="search-box-wrap">
    <div class="search-box">
      <p>キーワード検索</p>
     <div>
      <%= f.search_field :store_name_or_description_cont, placeholder: "キーワードを入力して下さい", class: "form-control" %>
     </div>
      <%= f.submit '検索', class:"keyword-search-btn" %>
    </div>
  </div>
<% end %>

<div class="list-wrapper">
  <% if @p.result.exists? %>
    <div class="header-list-content">
      <h2 class="header-list-text">
        施設一覧画面
        <p class="list-text-head">※各施設名または写真をクリックすると詳細ページへアクセスできます！</p>
      </h2>
    </div>
  <% end %>

  <ul class="list-page-wrap">
  <% if @results.length != 0 %>
    <% @results.each do |result| %>
      <li class="list-list">
        <div class="store-img-content">
          <%= link_to image_tag(result.image, class: "store-img"), store_path(result) %>
        </div>
        <div class="store-name-content">
          <div class="name-content"><%= link_to result.store_name, store_path(result) %></div>
          <div class="desc-content"><%= result.description %></div>
        </div>
      </li>
    <% end %>
  </ul>
  <% else %>

  <div class="check-wrap">
    <p class="empty-result">該当する施設はありませんでした。</p>

    <div class="back-top-page">
      <%= link_to "TOPページへ戻る", root_path, class: "back-text" %>
    </div>
  </div>
  <% end %>
</div>

app/views/stores/searching_prefecture.html.erb
<%= render "shared/header_logo" %>

<%= search_form_for @p, url: searching_prefecture_stores_path do |f| %>
  <div class="search-box-wrap">
    <div class="search-box">
      <p>都道府県検索</p>
      <%= f.collection_select :prefecture_id_eq, Prefecture.all, :id, :name, {include_blank: '指定なし'},{class:"select-box", id:"prefecture-categorty"} %>
      <br>
      <%= f.submit '検索', class:"prefecture-search-btn" %>
    </div>
  </div>
<% end %>

<div class="list-wrapper">
  <% if @p.result.exists? %>
    <div class="header-list-content">
      <h2 class="header-list-text">
        施設一覧画面
        <p class="list-text-head">※各施設名または写真をクリックすると詳細ページへアクセスできます！</p>
      </h2>
    </div>
  <% end %>

  <ul class="list-page-wrap">
  <% if @results.length != 0 %>
    <% @results.each do |result| %>
      <li class="list-list">
        <div class="store-img-content">
          <%= link_to image_tag(result.image, class: "store-img"), store_path(result) %>
        </div>
        <div class="store-name-content">
          <div class="name-content"><%= link_to result.store_name, store_path(result) %></div>
          <div class="desc-content"><%= result.description %></div>
        </div>
      </li>
    <% end %>
  </ul>
  <% else %>

  <div class="check-wrap">
    <p class="empty-result">該当する施設はありませんでした。</p>

    <div class="back-top-page">
      <%= link_to "TOPページへ戻る", root_path, class: "back-text" %>
    </div>
  </div>
  <% end %>
</div>

app/views/stores/show.html.erb
<%= render "shared/header_logo" %>

<div class="show-main-container">
  <div class="detail-warp">
    <div class="detail-img">
      <%= image_tag @store.image, class: "img-detail" %>
    </div>

    <table class="detail-table-store">
      <tbody>
        <tr>
          <th class="detail-list-store">施設名</th>
          <td class="detail-name-store"><%= @store.store_name %></td>
        </tr>

        <tr>
          <th class="detail-list-store">入浴料</th>
          <td class="detail-name-store"><%= @store.bathing_fee %>円</td>
        </tr>

        <tr>
          <th class="detail-list-store">サウナ室温度</th>
          <td class="detail-name-store"><%= @store.sauna_temp %>℃</td>
        </tr>

        <tr>
          <th class="detail-list-store">水風呂温度</th>
          <td class="detail-name-store"><%= @store.water_temp %>℃</td>
        </tr>

        <tr>
          <th class="detail-list-store">オートロウリュ</th>
          <td class="detail-name-store"><%= @store.rouryu.name %></td>
        </tr>

        <tr>
          <th class="detail-list-store">外気浴スペース</th>
          <td class="detail-name-store"><%= @store.outside_bath.name %></td>
        </tr>

        <tr>
          <th class="detail-list-store">休憩スペース</th>
          <td class="detail-name-store"><%= @store.break_space.name %></td>
        </tr>

        <tr>
          <th class="detail-list-store">都道府県</th>
          <td class="detail-name-store"><%= @store.prefecture.name %></td>
        </tr>

        <tr>
          <th class="detail-list-store">住所</th>
          <td class="detail-name-store"><%= @store.address %></td>
        </tr>

        <tr>
          <th class="detail-list-store">電話番号</th>
          <td class="detail-name-store"><%= @store.phone_number %></td>
        </tr>

      </tbody>
    </table>

    <div class="detail-desc">
      <span class="box-title">おすすめポイント!</span>
      <p><%= @store.description %></p>
    </div>
  </div>

<div class="comment-wrap">
  <div class="send-warp">
    <% if user_signed_in? %>
      <%= link_to "コメント投稿する", new_store_comment_path(@store), class: "send-btn" %>
    <% end %>
  </div>

  <div class="border-line"></div>

  <h3 class="comment-header-text">コメント一覧</h3>
    <% @comments.each do |comment| %>
      <div class="comment-detail">
        <div class="nickname-user"><%= link_to comment.user.nickname, user_path(comment.user_id) %></div>
        <div class="baloon">
          <div class="date-time"><%= comment.created_at.strftime("%Y-%m-%d %H:%M:%S") %></div>
          <br>
          <div class="comment-txt"><%= comment.text %></div>
          <div class="star-icon" id="star-rate-<%= comment.id %>"></div>
            <script>
            $('#star-rate-<%= comment.id %>').raty({
              size: 36,
              starOff:  '<%= asset_path('star-off.png') %>',
              starOn : '<%= asset_path('star-on.png') %>',
              starHalf: '<%= asset_path('star-half.png') %>',
              half: true,
              readOnly: true,
              score: <%= comment.evaluation %>,
            });
            </script>
        </div>
      </div>

    <% end %>
</div>