config/routes.rb
Rails.application.routes.draw do
  root to: "stores#index"
  devise_for :users, controllers:{  registrations:'users/registrations'  }
  resources :stores, only: [:index, :new, :create, :show] do
    collection do
      get 'list', 'check', 'search_keyword', 'searching_keyword', 'search_prefecture', 'searching_prefecture', 'search_bathing_fee', 'searching_bathing_fee'
    end
    resources :comments, only: [:new, :create]
  end
  resources :users, only: [:index, :show] do
    collection do
      get 'check', 'check_edit'
    end
    member do
      get 'unsubscribe', 'list'
    end
    member do
      patch 'withdrawal'
    end
  end
  resources :events, only: [:show, :new, :create]
end

app/models/user.rb
class User < ApplicationRecord
  has_many :stores
  has_many :comments
  has_one :event

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :period

  with_options presence: true do
    validates :nickname
    validates :birthday
    validates :introduce, length: { maximum: 200 }
    VALID_NAME_REGIX = /\A[ぁ-んァ-ヶ一-龥々ー]+\z/
    with_options format: { with: VALID_NAME_REGIX, message: 'は全角文字を入力して下さい' } do
      validates :last_name
      validates :first_name
    end
  end

  with_options numericality: { other_than: 1, message: 'の項目は---以外を入力して下さい' } do
    validates :period_id
  end

  VALID_PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?[A-Z])(?=.*?\d)\w{6,12}\z/
  validates :password,
            format: { with: VALID_PASSWORD_REGEX, message: 'は無効です 6~12字以内で半角の英大文字、英小文字、数字のみを含んでいる必要があります' }, allow_nil: true, on: :create

  validates :is_deleted, inclusion: { in: [true, false] }

  def active_for_authentication?
    super && (is_deleted == false)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  def after_sign_up_path_for(_resource)
    check_users_path
  end

  def update_resource(resource, params)
    resource.update_without_password(params)
  end

  def after_update_path_for(_resource)
    check_edit_users_path
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show, :list, :unsubscribe, :withdrawal]
  before_action :set_params, only: [:show, :list, :unsubscribe, :withdrawal]
  before_action :check_user, only: [:list, :unsubscribe, :withdrawal]

  require 'date'

  def index
  end

  def show
  end

  def list
    @comments = @user.comments.includes(:store).order('created_at DESC')
  end

  def unsubscribe
  end

  def withdrawal
    @user.update(is_deleted: true)
    date_time = DateTime.now
    deleted_email = @user.email + date_time.strftime('%Y%m%d%H%M')
    @user.update(email: deleted_email)
    reset_session
    flash[:notice] = '退会処理を実行いたしました'
    redirect_to root_path
  end
end

def check
end

def check_edit
end

private

def set_params
  @user = User.find(params[:id])
end

def check_user
  redirect_to root_path unless current_user.id == @user.id
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/check.html.erb
<%= render "shared/header_logo" %>

<div class="check-wrap">
  <div class="user-register">
    <h3>ユーザー登録が正常に完了しました！！</h3>
    <p>※尚、こちらにご登録された情報はマイページ編集でいつでも変更可能です。</p>
  </div>

  <div class="back-top-page">
    <%= link_to "TOPページへ戻る", root_path, class: "back-text" %>
  </div>
</div>

app/views/users/check_edit.html.erb
<%= render "shared/header_logo" %>

<div class="check-wrap">
  <div class="user-register">
    <h3>ユーザー情報の変更を正常に完了しました！！</h3>
  </div>

  <div class="back-top-page">
    <%= link_to "TOPページへ戻る", root_path, class: "back-text" %>
  </div>
</div>

app/views/users/index.html.erb
<main class="quiz-background">
<div class="header-content-quiz">
  <%= render "shared/header_logo" %>
</div>

  <section class="quiz-text-head">
    <div class="quiz-heading">
      3択クイズ挑戦中！！
    </div>
  </section>

  <section class="quiz-container">
    <p id="question"></p>
    <ul id="choices"></ul>
    <div id="btn" class="disabled">NEXT</div>

    <section id="result" class="hidden">
      <p></p>
      <a href="">もう1回トライ！</a>
      <a href="/stores" class="result-under-text"><h5>TOPページへ戻る<h5></a>
    </section>
  </section>
</main>

app/views/users/list.html.erb
<%= render "shared/header_logo" %>

<div class="post-page-wrap">
  <div class="post-comment-head">
    <h1 class="post-comment-letter">コメント一覧ページ</h1>
    <p>※各施設名クリックして頂くと詳細ページへ遷移します。</p>
  </div>

  <div class="post-wrap">
    <% @comments.each do |comment| %>
      <div class="post-comment">
        <div>
          投稿した施設名 : 
          <span class="post-store-name">
            <%= link_to comment.store.store_name, store_path(comment.store.id) %>
          </span>
        </div>
        

        <div class="post-text">
          <%= comment.text %>
        </div>

        <div>
          <%= comment.created_at.strftime("%Y-%m-%d %H:%M:%S") %>
        </div>

        <div class="star-icon" id="star-rate-<%= comment.id %>">
        </div>
            <script>
            $('#star-rate-<%= comment.id %>').raty({
              size: 36,
              starOff:  '<%= asset_path('star-off.png') %>',
              starOn : '<%= asset_path('star-on.png') %>',
              starHalf: '<%= asset_path('star-half.png') %>',
              half: true,
              readOnly: true,
              score: <%= comment.evaluation %>,
            });
            </script>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% if @user.is_deleted == false %>
<%= render "shared/header_logo" %>
  <div class="user-show-top">
    <% if current_user.id == @user.id %>
      <ul class="user-show-list">
        MENU
        <li class="show-list"><span><i class="fas fa-chevron-down"></i></span>
          <ul class="list-detail">
            <li class="list-single"><%= link_to "マイページ編集", edit_user_registration_path %></li>
            <li class="list-single"><%= link_to "マイカレンダー", event_path(current_user.id) %></li>
            <li class="list-single"><%= link_to "コメント一覧", list_user_path(@user) %></li>
            <li class="list-single"><%= link_to "会員退会", unsubscribe_user_path(current_user.id) %></li>
          </ul>
        </li>
      </ul>
    <% end %>
  </div>


  <div class="user-detail-wrapper">
    <div class="user-detail-head">
      <div class="user-head-text">
        ユーザー詳細ページ
      </div>

      <% if current_user.id == @user.id %>
        <table class="detail-table-user">
          <tbody>

            <tr>
              <th class="detail-list-user">お名前</th>
              <td class="detail-name-user"><%= @user.last_name %>  <%= current_user.first_name %></td>
            </tr>

            <tr>
              <th class="detail-list-user">生年月日</th>
              <td class="detail-name-user"><%= @user.birthday %></td>
            </tr>

            <tr>
              <th class="detail-list-user">メールアドレス</th>
              <td class="detail-name-user"><%= @user.email %></td>
            </tr>

            <tr>
              <th class="detail-list-user">ニックネーム</th>
              <td class="detail-name-user"><%= @user.nickname %></td>
            </tr>

            <tr>
              <th class="detail-list-user">サ活エリア</th>
              <td class="detail-name-user"><%= @user.my_area %></td>
            </tr>

            <tr>
              <th class="detail-list-user">サ活歴</th>
              <td class="detail-name-user"><%= @user.period.name %></td>
            </tr>

            <tr>
              <th class="detail-list-user">自己紹介文</th>
              <td class="detail-name-user"><%= @user.introduce %></td>
            </tr>

          </tbody>
        </table>
      <% else %>
        <table class="detail-table-user">
          <tbody>
            <tr>
                <th class="detail-list-user">ニックネーム</th>
                <td class="detail-name-user"><%= @user.nickname %></td>
              </tr>
              <tr>
                <th class="detail-list-user">サ活エリア</th>
                <td class="detail-name-user"><%= @user.my_area %></td>
              </tr>
              <tr>
                <th class="detail-list-user">サ活歴</th>
                <td class="detail-name-user"><%= @user.period.name %></td>
              </tr>
              <tr>
                <th class="detail-list-user">自己紹介文</th>
                <td class="detail-name-user"><%= @user.introduce %></td>
              </tr>
          </tbody>
      <% end %>
    </div>
  </div>
<% else %>
  <div class="erase-wrap">
  <%= render "shared/header_logo" %>
    <div class="erase-user">
      該当するページは存在しません。
      <p class="erase-user-text">
        ※既にユーザーが退会している可能性があります。
      </p>
    </div>
  </div>
<% end %>

app/views/users/unsubscribe.html.erb
<%= render "shared/header_logo" %>

<div class="procedure">
  <h2>退会お手続き</h2>
  <p>
    退会手続きをされますと、全てのサービスがご利用いただけなくなります。<br>
    再度ご利用をいただく場合には、新規登録のお手続きが必要になります。<br>
    本当に退会してよろしいですか？
  </p>
</div>

  <div class="withdrawal-wrap">
    <div class="withdrawal-btn"><%= link_to "退会する", withdrawal_user_path(@user), method: :patch %></div>
    <div class="no-withdrawal-btn"><%= link_to "退会しない", user_path(current_user) %></div>
  </div>

<footer class="footer-container">
  <div class="copy-rights"><%= render "shared/footer_logo"%></div>
</footer>